site_name: Sapoconcho | Bricolabs
site_url: https://sapoconcho.bricolabs.cc/
repo_name: Sapoconcho's GitHub
repo_url: https://github.com/brico-labs/sapoconcho
edit_uri: ""
site_description: Sapoconcho is an open-source learning robot.
theme:
    name: material
    palette:
        //primary: yellow
        //accent: yellow
        //scheme: slate
    favicon: img/favicon.ico
    logo: img/logo.png
extra_css:
    - stylesheets/extra.css
markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
nav:
    - Inicio: index.md
    - Kit: kit.md
    - Montaje: montaje.md
    - Programación: programacion.md
    - Taller: taller.md
    - Equipo: equipo.md