site_name: Sapoconcho
site_url: https://sapoconcho.bricolabs.cc/
theme:
    name: readthedocs
nav:
    - Inicio: index.md
    - Kit: kit.md
    - Montaje: montaje.md
    - Programación: programacion.md
    - Taller: taller.md
    - About: about.md