site_name: Sapoconcho | Bricolabs
site_url: https://sapoconcho.bricolabs.cc/
repo_name: Sapoconcho's GitHub
repo_url: https://github.com/brico-labs/sapoconcho
edit_uri: ""
site_description: Sapoconcho is an open-source learning robot.
theme:
    name: material
    favicon: img/favicon.ico
    logo: img/logo_topbar.png
    language: es
extra_css:
    - stylesheets/extra.css
markdown_extensions:
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight:
        anchor_linenums: true
extra:
  generator: false
nav:
    - Inicio: index.md
    - Historia: historia.md
    - Kit: kit.md
    - Montaje: montaje.md
    - Programación: programacion.md
    - Taller: taller.md
    - Equipo: equipo.md