site_name: Sapoconcho
site_url: https://sapoconcho.bricolabs.cc/
repo_name: Sapoconcho's GitHub
repo_url: https://github.com/brico-labs/sapoconcho
edit_uri: 'edit/main/docs/'
site_description: Sapoconcho is an open-source learning robot.
theme:
    name: readthedocs
extra_css: [extra.css]
nav:
    - Inicio: index.md
    - Kit: kit.md
    - Montaje: montaje.md
    - Programación: programacion.md
    - Taller: taller.md
    - Equipo: equipo.md